#!/usr/bin/perl -w
# -*- perl -*-

=head1 NAME

hq_uptime - Munin plugin to monitor system uptime.

=head1 APPLICABLE SYSTEMS

Linux systems.

=head1 CONFIGURATION

Not needed.

=head1 VERSION

  20151014.01

=head1 MAGIC MARKERS

  #%# family=manual
  #%# capabilities=autoconf

=head1 BUGS

None.

=head1 AUTHOR

Pirx Developers - https://pirx.dev/

=head1 LICENSE

See attached LICENSE file for details or visit
http://munin.furud.net/

=cut

use strict;

# Handle autoconf
if(defined($ARGV[0]) and $ARGV[0] eq 'autoconf') {
  print("yes\n");
  exit(0);
}

# Get current uptime
my $uptime = `cut -d' ' -f 1 /proc/uptime 2>/dev/null`;
chomp($uptime);
$uptime = $uptime / 86400;
 
# Handle config
if(defined($ARGV[0]) and $ARGV[0] eq 'config') {
  print <<EOF;
graph_title System uptime
graph_args --base 1000 --lower-limit 0
graph_scale no
graph_vlabel days
graph_category system

uptime.label Uptime
uptime.type GAUGE
uptime.min 0
uptime.draw AREA
uptime.colour 00d000
EOF
  exit(0);
}

printf("uptime.value %.2f\n", $uptime);

exit(0);
